version: '3.8'

services:
  webapi:
    build:
      context: ./ApiAspNet
      dockerfile: ./Dockerfile
    container_name: aspnetcore-api
    ports:
      - "5000:80"
    depends_on:
      - elasticsearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - elknet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elknet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.20
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elknet

volumes:
  esdata:

networks:
  elknet:
